const labels={PRIMARY_AGREEMENT:'本命一致',AGENT_DISAGREEMENT:'本命不一致',CANDIDATE_OVERLAP:'候補重複',BOTH_TOP3:'両者TOP3支持',CROSS_AGENT_TOP5:'両者TOP5支持',DIVERSE_SIGNAL_SUPPORT:'異なる分析視点から支持'};
const names={pachio:'パチお',pachiko:'パチこ',pachikamisama:'パチ神様'};let data={};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>v==null?'—':typeof v==='number'?v.toFixed(2):esc(v);
const tags=a=>(a?.reason_codes||[]).map(c=>`<span class="reason">${esc(labels[c]||c)}</span>`).join('')||'<span class="muted small">根拠データなし</span>';
const result=v=>v==='success'?'<span class="result-success">勝ち</span>':v==='failure'?'<span class="result-failure">負け</span>':'<span class="pending">結果待ち</span>';
function candidates(a){return (a?.candidates||[]).slice(0,5).map((c,i)=>`<div class="candidate"><span>${i+1}位　<strong>${esc(c.machine)}</strong></span><span>${num(c.score)}</span></div>`).join('')||'<span class="muted">候補なし</span>'}
function card(key,a,r){const machine=key==='pachikamisama'?a?.honmei:a?.primary_machine,actual=key==='pachikamisama'?r?.honmei:r?.result;return `<article class="card"><h2>${names[key]}</h2><div class="machine">${machine?esc(machine):'未選出'}</div><p>信頼度　<strong>${num(a?.confidence)}</strong></p><p>${esc(a?.comment||'コメントなし')}</p><div>${tags(a)}</div>${key==='pachikamisama'?`<p>対抗 <strong>${esc(a?.taikou||'なし')}</strong>　穴 <strong>${esc(a?.ana||'なし')}</strong></p><p class="small">本命：${result(actual?.outcome)}</p>`:`<h3>上位候補</h3>${candidates(a)}<p class="small">実績：${result(actual?.outcome)}</p>`}</article>`}
function stat(key){const s=data.experience?.agents?.[key]?.summary;if(!s)return `<div class="card"><h3>${names[key]}</h3><p class="muted">経験記憶はまだありません</p></div>`;return `<div class="card"><h3>${names[key]}</h3><div class="stat">${s.win_rate==null?'—':(s.win_rate*100).toFixed(1)+'%'}</div><p>${s.success}勝 ${s.failure}敗　評価済み${s.evaluated_count}件</p><p class="small">現在：${esc(s.current_streak?.type||'なし')} ${s.current_streak?.count||0}連</p></div>`}
function render(view){const p=data.prediction,r=data.result;if(view==='home')document.querySelector('#app').innerHTML=p?`<section class="section"><div class="card"><strong>予測日 ${esc(p.prediction_date)}</strong>　cutoff ${esc(p.cutoff_date)}　<span class="tag">locked</span></div></section><section class="grid">${card('pachio',p.agents?.pachio,r?.agents?.pachio)}${card('pachiko',p.agents?.pachiko,r?.agents?.pachiko)}${card('pachikamisama',p.agents?.pachikamisama,r?.agents?.pachikamisama)}</section>`:'<div class="empty"><h2>予測データがありません</h2><p>locked済みのpredictionを保存すると、ここに表示されます。</p></div>';
else if(view==='ranking')document.querySelector('#app').innerHTML=`<h2>戦績／ランキング</h2><section class="grid">${stat('pachio')}${stat('pachiko')}<div class="card"><h3>パチ神様（本命）</h3>${data.experience?.pachikamisama?.roles?.honmei?`<div class="stat">${((data.experience.pachikamisama.roles.honmei.win_rate||0)*100).toFixed(1)}%</div><p>${data.experience.pachikamisama.roles.honmei.success}勝 ${data.experience.pachikamisama.roles.honmei.failure}敗</p>`:'<p class="muted">経験記憶はまだありません</p>'}</div></section>`;
else if(view==='diary'){const refs=data.experience?.reflections||[];document.querySelector('#app').innerHTML=`<h2>実戦日記</h2>${refs.length?refs.slice().reverse().map(x=>`<article class="card section"><h3>${esc(x.date)}</h3>${(x.events||[]).map(e=>`<span class="reason">${esc(labels[e.event]||e.event)}</span>`).join('')}</article>`).join(''):'<div class="empty">評価済みの実戦日記はまだありません。</div>'}`}
else{document.querySelector('#app').innerHTML=`<h2>詳細分析</h2><section class="grid">${['pachio','pachiko','pachikamisama'].map(k=>`<article class="card"><h3>${names[k]}</h3><pre class="small">${esc(JSON.stringify(data.prediction?.agents?.[k]||{},null,2))}</pre></article>`).join('')}</section>`}}
document.querySelectorAll('.tabs button[data-view]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.view)}));
fetch('/api/dashboard').then(r=>r.json()).then(v=>{data=v;document.querySelector('#mode').textContent=v.meta.mode;render('home')}).catch(()=>{document.querySelector('#app').innerHTML='<div class="empty">データを読み込めませんでした。</div>'});
